c    $Id: common_drive.inc 16 2007-10-18 12:36:47Z centler $
           common/dr1/optftol,problim,relsig,stdmin,perturb
              common/dr2/iopt,iof,itmax,nts,kmast
             common/dr3/tfact,etol,ftol,ssrelax,alphaCN,uc
             common/dr4/isol,newton,isplit,ngtzero,ilud
             common/dr5/nsstate,itssmax,itintmax,idrdc,istst

           integer iopt,iof,itmax,nts,kmast,isplit,ngtzero,ilud
             integer nsstate,isol,newton,itssmax,itintmax,idrdc,istst
           real*8 optftol,problim,relsig,stdmin,perturb
             real*8 tfact,etol,ftol,ssrelax,alphaCN,uc

             

        